name: Python CI Tests
run-name: ${{ github.actor }} is testing out Github Actions
on:
  push:
    branches: [main, dev]

jobs:
  build:
    name: Lint and Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3          
          curl -LsSf https://astral.sh/uv/install.sh >> install.sh
          chmod +x install.sh
          ./install.sh
          uv venv
          source .venv/bin/activate
          uv pip install -r requirements.txt
          make inclusive

      - name: Run the linter
        run: make lint

      - name: Execute Unit tests
        run: make test

      - name: Post-checkout messages
        run: |
          echo "Looks like your tests on ${{ github.repository }} were all good!"
          echo "FINAL STATUS: ${{ job.status }}"
